INSERT INTO [dbo].[StudentPredmet] ([StudentId], [PredmetId]) VALUES (1000, N'BOOP ')
INSERT INTO [dbo].[StudentPredmet] ([StudentId], [PredmetId]) VALUES (1000, N'BPC1T')
INSERT INTO [dbo].[StudentPredmet] ([StudentId], [PredmetId]) VALUES (1001, N'BOOP ')
INSERT INTO [dbo].[StudentPredmet] ([StudentId], [PredmetId]) VALUES (1002, N'BOOP ')
INSERT INTO [dbo].[StudentPredmet] ([StudentId], [PredmetId]) VALUES (1003, N'BANA ')
INSERT INTO [dbo].[StudentPredmet] ([StudentId], [PredmetId]) VALUES (1003, N'BPC1T')
