INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1000, N'Josef', N'Novák', N'1995-01-01')
INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1001, N'Jan', N'Novotný', N'1996-02-25')
INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1002, N'Albert', N'Einstein', N'1997-01-01')
INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1003, N'Isaac', N'Newton', N'1993-01-04')
INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1004, N'Pavla', N'Nová', N'1994-07-05')
INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1005, N'Karel', N'Novák', N'1994-05-05')
INSERT INTO [dbo].[Student] ([StudentId], [Jmeno], [Prijmeni], [DatumNarozeni]) VALUES (1006, N'Karel', N'Novotný', N'1994-05-06')
